# Generated by Django 5.1.7 on 2025-04-29 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="details",
            name="travel_preference",
            field=models.CharField(
                choices=[
                    ("solo", "Solo"),
                    ("family", "Family"),
                    ("friends", "Friends"),
                    ("romantic", "Romantic"),
                    ("adventure", "Adventure"),
                    ("luxury", "Luxury"),
                ],
                default="solo",
                max_length=10,
            ),
        ),
    ]
