# Generated by Django 5.1.7 on 2025-04-20 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My Itinerary', max_length=200)),
                ('destination', models.CharField(blank=True, max_length=200)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('star_rating', models.CharField(blank=True, max_length=10)),
                ('review_count', models.PositiveIntegerField(blank=True, default=0)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20)),
                ('region', models.CharField(choices=[('europe', 'Europe'), ('asia', 'Asia'), ('africa', 'Africa'), ('antarctica', 'Antarctica'), ('north-america', 'North America'), ('south-america', 'South America'), ('australia', 'Australia'), ('mid-east', 'Middle East'), ('pacific', 'Pacific')], max_length=75)),
                ('start_date', models.DateField(help_text='Optional start date of the itinerary')),
                ('end_date', models.DateField(help_text='Optional end date of the itinerary')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The time this itinerary was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='The time this itinerary was last updated.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
