# Generated by Django 5.1.7 on 2025-03-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itinerary',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='length',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='title',
        ),
        migrations.RemoveField(
            model_name='itinerary',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='itinerary',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='Duration in days'),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='name',
            field=models.CharField(default='My Itinerary', max_length=200),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='star_rating',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='itinerary',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='itinerary',
            name='destination',
            field=models.CharField(max_length=200),
        ),
    ]
