# Generated by Django 5.1.7 on 2025-04-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='user',
            field=models.CharField(default='Anonymous', max_length=150),
        ),
    ]
