# Generated by Django 5.1.7 on 2025-04-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_itinerary_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='details',
            field=models.TextField(blank=True, help_text='Detailed description of the itinerary'),
        ),
    ]
