# Generated by Django 5.1.7 on 2025-04-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_itinerary_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerary',
            name='save_model',
            field=models.BooleanField(default=False, help_text='Is this itinerary saved?'),
        ),
    ]
