# Generated by Django 5.1.7 on 2025-04-22 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_itinerary_save_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itinerary',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
